#!/bin/sh /etc/rc.common

START=20

start() {
    local board=$(board_name)

	case $board in
	glinet,gl-mt6000)
		echo 2 > /proc/irq/120/smp_affinity
		echo 8 > /proc/irq/121/smp_affinity
		logger -t smp_affinity "Set irq 120 to CPU1 and irq 121 to CPU3"
        ;;
    esac
}
